[theme]
primaryColor = "#FF69B4"  # Pink
backgroundColor = "#000000" # Black
secondaryBackgroundColor = "#FFFFFF" # White
textColor = "#FFFFFF" # White
font = "sans serif" # Streamlit does not directly support Architype Annette

[app]
file = "streamlit_app.py"